version: 3.8

services:
  db:
    image: postgres:alpine
    container_name: "crudserver"
    ports:
      - "5614:5614"
    environment:
      - POSTGRES_DB=crudserverdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
    networks:
      - fullstack

  server:
